//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Dogovor = new HashSet<Dogovor>();
        }
    
        public int id_client { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int paspoport_number { get; set; }
        public int pasport_seria { get; set; }
        public string phone { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Dogovor> Dogovor { get; set; }
    }
}
