//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogovor
    {
        public Dogovor()
        {
            this.Tovar = new HashSet<Tovar>();
        }
    
        public int Id_Dogovor { get; set; }
        public int Id_Client { get; set; }
        public int Id_Sotrudnik { get; set; }
        public Nullable<System.DateTime> date_dogovor { get; set; }
        public Nullable<System.DateTime> date_srokzaloga { get; set; }
        public string procent { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Tovar> Tovar { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
