//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        public Sotrudnik()
        {
            this.Dogovor = new HashSet<Dogovor>();
        }
    
        public int Id_Sotrudnik { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Dogovor> Dogovor { get; set; }
    }
}
