//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int Id_Tovar { get; set; }
        public int Id_dogovor { get; set; }
        public string Name_Tovar { get; set; }
        public string price { get; set; }
        public int Id_Category { get; set; }
        public string status { get; set; }
        public string Img { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Dogovor Dogovor { get; set; }
    }
}
